version: '2'

services:
  rdb:
    image: rethinkdb
    ports:
      - "58081:8080"
      - "28015"
    volumes:
      - /data/rethinkdb58081:/data
      - /etc/rethinkdb/instances.d/default.conf:/etc/rethinkdb/instances.d/default.conf

  bdb:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: docker-bigchaindb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
      - ./docs:/usr/src/app/docs
      - ./setup.py:/usr/src/app/setup.py
      - ./setup.cfg:/usr/src/app/setup.cfg
      - ./pytest.ini:/usr/src/app/pytest.ini
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - /data/localdb/:/data/localdb/
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_API_ENDPOINT: http://bdb:9984/api/v1
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
    ports:
      - "9984"
    # command: bash -c "./wait-for-it.sh  && unichain start"
    command: ["./wait-for-it.sh", "127.0.0.1:58080", "--", "unichain start"]
