version: '2'

services:
  rdb:
    image: rethinkdb
    volumes:
      - /uni_docker/rethinkdb_data:/data
      - /uni_docker/rethinkdb/default.conf:/etc/rethinkdb/instances.d/default.conf
    command: rethinkdb --bind all --config-file /etc/rethinkdb/instances.d/default.conf
    network_mode: "host"

  bdb:
    image: unichain_bdb
    container_name: docker-bigchaindb
    volumes:
      - /uni_docker/.unichain:/etc/unichain/.unichain
    environment:
      BIGCHAINDB_CONFIG_PATH: /etc/unichain/.unichain
    command: bash -c "unichain start & unichain_api start"
    network_mode: "host"

  bdb_init:
    image: unichain_bdb
    volumes:
      - /uni_docker/.unichain:/etc/unichain/.unichain
    environment:
      BIGCHAINDB_CONFIG_PATH: /etc/unichain/.unichain
    command: bash -c "unichain init && unichain set-shards $NUM_SHARDS && unichain set-replicas $NUM_REPLICAS"
    network_mode: "host"
