version: '2'

services:
  rdb:
    image: hub.c.163.com/library/rethinkdb
    volumes:
      - /uni_docker/rethinkdb_data:/data
      - /uni_docker/default.conf:/etc/rethinkdb/instances.d/default.conf
    command: rethinkdb --bind all --config-file /etc/rethinkdb/instances.d/default.conf
    network_mode: "host"

  bdb:
    image: unichain_bdb
    container_name: docker-bigchaindb
    volumes:
      - /uni_docker/.unichain:/etc/unichain/.unichain
    environment:
      BIGCHAINDB_CONFIG_PATH: /etc/unichain/.unichain
    ports:
      - "9984:9984"
    command: bash -c "unichain start & unichain_api start"
    network_mode: "host"
